const express = require('express')
const app= express()
const cors = require('cors')
const foodRoute = require('./routes/food.route')
const authRoute = require('./routes/user.route')
const reqRoute = require('./routes/request.route')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/food',foodRoute)
app.use('/auth',authRoute)
app.use('/request',reqRoute)
app.listen(5000)
