const express = require('express')
const app= express()
const cors = require('cors')
const foodRoute = require('./routes/food.route')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/food',foodRoute)
app.listen(3000)
